apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  GREETING: Config-Buenos
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: myapp
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DATABASE_URI: {{ .Values.postgres.uri | quote }}
  DATABASE_INIT_URI: {{ .Values.postgres.init_uri | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}

