apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  GREETING: Config-Alloha
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: myapp
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXNxbCtwc3ljb3BnMjovL215dXNlcjpwYXNzd2RAcG9zdGdyZXM6NTQzMi9teWFwcA==
  DATABASE_INIT_URI: cG9zdGdyZXNxbDovL215dXNlcjpwYXNzd2RAcG9zdGdyZXM6NTQzMi9teWFwcA==
  POSTGRES_USER: bXl1c2Vy
  POSTGRES_PASSWORD: cGFzc3dk

